// login
export const DO_LOGIN = 'DO_LOGIN'
export const DO_LOGIN_SUCCESS = 'DO_LOGIN_SUCCESS'
export const DO_LOGIN_ERROR = 'DO_LOGIN_ERROR'
export const TOKEN_LOGIN = 'TOKEN_LOGIN'
export const TOKEN_LOGIN_SUCCESS = 'TOKEN_LOGIN_SUCCESS'
export const TOKEN_LOGIN_ERROR = 'TOKEN_LOGIN_ERROR'

// tickets
export const FETCH_TICKETS = 'FETCH_TICKETS'
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS'
export const FETCH_TICKETS_ERROR = 'FETCH_TICKETS_ERROR'

// product
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR'
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const ADD_PRODUCT_TO_CART_SUCCESS = 'ADD_PRODUCT_TO_CART_SUCCESS'
export const ADD_PRODUCT_TO_CART_ERROR = 'ADD_PRODUCT_TO_CART_ERROR'


// cart
export const FETCH_CART_PRODUCTS = 'FETCH_CART_PRODUCTS'
export const FETCH_CART_PRODUCTS_SUCCESS = 'FETCH_CART_PRODUCTS_SUCCESS'
export const FETCH_CART_PRODUCTS_ERROR = 'FETCH_CART_PRODUCTS_ERROR'



