// login
export const DO_LOGIN = 'DO_LOGIN'
export const DO_LOGIN_SUCCESS = 'DO_LOGIN_SUCCESS'
export const DO_LOGIN_ERROR = 'DO_LOGIN_ERROR'
export const TOKEN_LOGIN = 'TOKEN_LOGIN'
export const TOKEN_LOGIN_SUCCESS = 'TOKEN_LOGIN_SUCCESS'
export const TOKEN_LOGIN_ERROR = 'TOKEN_LOGIN_ERROR'

// tickets
export const FETCH_TICKETS = 'FETCH_TICKETS'
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS'
export const FETCH_TICKETS_ERROR = 'FETCH_TICKETS_ERROR'



