// login
export const DO_LOGIN = 'DO_LOGIN'
export const DO_LOGIN_SUCCESS = 'DO_LOGIN_SUCCESS'
export const DO_LOGIN_ERROR = 'DO_LOGIN_ERROR'

export const TOKEN_LOGIN = 'TOKEN_LOGIN'
export const TOKEN_LOGIN_SUCCESS = 'TOKEN_LOGIN_SUCCESS'
export const TOKEN_LOGIN_ERROR = 'TOKEN_LOGIN_ERROR'

// tickets
export const FETCH_TICKETS = 'FETCH_TICKETS'
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS'
export const FETCH_TICKETS_ERROR = 'FETCH_TICKETS_ERROR'

// product
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR'

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const ADD_PRODUCT_TO_CART_SUCCESS = 'ADD_PRODUCT_TO_CART_SUCCESS'
export const ADD_PRODUCT_TO_CART_ERROR = 'ADD_PRODUCT_TO_CART_ERROR'

// cart
export const FETCH_CART_PRODUCTS = 'FETCH_CART_PRODUCTS'
export const FETCH_CART_PRODUCTS_SUCCESS = 'FETCH_CART_PRODUCTS_SUCCESS'
export const FETCH_CART_PRODUCTS_ERROR = 'FETCH_CART_PRODUCTS_ERROR'

export const CHANGE_CART_PRODUCT_CHECKED = 'CHANGE_CART_PRODUCT_CHECKED'
export const CHANGE_CART_PRODUCT_CHECKED_SUCCESS = 'CHANGE_CART_PRODUCT_CHECKED_SUCCESS'
export const CHANGE_CART_PRODUCT_CHECKED_ERROR = 'CHANGE_CART_PRODUCT_CHECKED_ERROR'

export const CHANGE_CART_ALL_PRODUCTS_CHECKED = 'CHANGE_CART_ALL_PRODUCTS_CHECKED'
export const CHANGE_CART_ALL_PRODUCTS_CHECKED_SUCCESS = 'CHANGE_CART_ALL_PRODUCTS_CHECKED_SUCCESS'
export const CHANGE_CART_ALL_PRODUCTS_CHECKED_ERROR = 'CHANGE_CART_ALL_PRODUCTS_CHECKED_ERROR'

export const CHANGE_CART_PRODUCT_NUMBER = 'CHANGE_CART_PRODUCT_NUMBER'
export const CHANGE_CART_PRODUCT_NUMBER_SUCCESS = 'CHANGE_CART_PRODUCT_NUMBER_SUCCESS'
export const CHANGE_CART_PRODUCT_NUMBER_ERROR = 'CHANGE_CART_PRODUCT_NUMBER_ERROR'

// my
export const FETCH_MY_PROFILE = 'FETCH_MY_PROFILE'
export const FETCH_MY_PROFILE_SUCCESS = 'FETCH_MY_PROFILE_SUCCESS'
export const FETCH_MY_PROFILE_ERROR = 'FETCH_MY_PROFILE_ERROR'

export const CHANGE_MY_DEFAULT_ADDRESS = 'CHANGE_MY_DEFAULT_ADDRESS'
export const CHANGE_MY_DEFAULT_ADDRESS_SUCCESS = 'CHANGE_MY_DEFAULT_ADDRESS_SUCCESS'
export const CHANGE_MY_DEFAULT_ADDRESS_ERROR = 'CHANGE_MY_DEFAULT_ADDRESS_ERROR'

export const CHANGE_MY_ADDRESS = 'CHANGE_MY_ADDRESS'
export const CHANGE_MY_ADDRESS_SUCCESS = 'CHANGE_MY_ADDRESS_SUCCESS'
export const CHANGE_MY_ADDRESS_ERROR = 'CHANGE_MY_ADDRESS_ERROR'

export const DELETE_MY_ADDRESS = 'DELETE_MY_ADDRESS'
export const DELETE_MY_ADDRESS_SUCCESS = 'DELETE_MY_ADDRESS_SUCCESS'
export const DELETE_MY_ADDRESS_ERROR = 'DELETE_MY_ADDRESS_ERROR'

export const ADD_MY_ADDRESS = 'ADD_MY_ADDRESS'
export const ADD_MY_ADDRESS_SUCCESS = 'ADD_MY_ADDRESS_SUCCESS'
export const ADD_MY_ADDRESS_ERROR = 'ADD_MY_ADDRESS_ERROR'



